spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/watchnest}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:watchnest}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:watchnest-local}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
